/**
 * @file icon_set_fixture.h
 *
 * Stands in for main/icons/icon_set_data.h, which this build cannot have.
 *
 * The real table is generated by tools/build_icon_set.py from artwork that is
 * not in the repository -- it is EPL-2.0 and this project is GPL-3.0 -- so a
 * fresh clone has no icon set at all, and tests written against the real one
 * would silently test nothing. icon_set.cpp takes ICON_SET_DATA_HEADER to name
 * this file instead; test/host/main/CMakeLists.txt defines it.
 *
 * Fourteen entries, shaped exactly like the generated ones and sorted by the
 * same rule (plain byte value -- icon_set.cpp binary searches them). Three
 * shapes of family, and each one is a real family from the classic set cut
 * down to size:
 *
 *   light        numeric steps AND named variants, the mixed case. openHAB
 *                ships light-0 through light-100 in tens, plus off and on.
 *   contact      named variants only -- as door, lock, presence and seventeen
 *                others also are.
 *   alarm        no variants at all.
 *
 * "contact" is in here for one reason. Its variants share the "contact-"
 * prefix and sit in the run that a numeric lookup walks, and strtoul("ajar")
 * is 0 -- so a lookup that did not insist on digits would answer contact-ajar
 * for every numeric state the icon is ever asked about. "light" cannot show
 * that on its own: the same bug reads light-off as 0 too, but 0 loses to
 * light-20 and the wrong answer never surfaces.
 *
 * Each icon's payload is its own name. The set never decodes what it stores --
 * it hands a pointer and a length to lodepng, which is somebody else's problem
 * -- so real PNGs here would test nothing that the generator's own round-trip
 * and ImageMagick cross-check do not already, and would make an assertion that
 * the right icon came back unreadable.
 */
#ifndef ICON_SET_FIXTURE_H
#define ICON_SET_FIXTURE_H

#define ICON_SET_GENERATED 1
#define ICON_SET_PIXEL_SIZE 32
#define ICON_SET_COUNT 14

/* Concatenated, in table order, with no separators: the offsets below index
 * into this and the sizes stop short of the next name. The trailing NUL a
 * string literal brings is not part of any entry, hence the -1. */
static const unsigned char icon_set_blob[] =
    "alarm"
    "contact"
    "contact-ajar"
    "contact-closed"
    "contact-open"
    "light"
    "light-0"
    "light-10"
    "light-100"
    "light-20"
    "light-90"
    "light-off"
    "light-on"
    "temperature";

#define ICON_SET_BLOB_SIZE (sizeof(icon_set_blob) - 1)

static const struct
{
    const char    *name;
    unsigned int   offset;
    unsigned short size;
} icon_set_table[ICON_SET_COUNT] = {
    { "alarm",            0u,  5u },
    { "contact",          5u,  7u },
    { "contact-ajar",    12u, 12u },
    { "contact-closed",  24u, 14u },
    { "contact-open",    38u, 12u },
    { "light",           50u,  5u },
    { "light-0",         55u,  7u },
    { "light-10",        62u,  8u },
    { "light-100",       70u,  9u },
    { "light-20",        79u,  8u },
    { "light-90",        87u,  8u },
    { "light-off",       95u,  9u },
    { "light-on",       104u,  8u },
    { "temperature",    112u, 11u },
};

#endif /* ICON_SET_FIXTURE_H */
