/**
 * @file icon_set.cpp
 *
 * See icon_set.hpp.
 */

#include "sdkconfig.h"

#include "icon_set.hpp"

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Generated by tools/build_icon_set.py, and absent until it has been run.
 *
 * __has_include rather than a CMake switch, so that the file appearing is the
 * whole of what turns the set on -- the same shape sim/icon_fixture.cpp uses
 * for its fixture data. main/CMakeLists.txt watches the directory as well, but
 * only so that a build started after the script ran recompiles this file and
 * says in its log what it found; nothing here depends on that having worked.
 *
 * CONFIG_OHEZ_ICONS_BUILTIN is the deliberate off switch, for measuring what
 * the set costs in flash against what it saves in requests.
 *
 * ICON_SET_DATA_HEADER names a different table, and exists for exactly one
 * caller: test/host, which cannot use the real one. The artwork is not in the
 * repository, so a working copy that has not run the generator -- a CI job, a
 * fresh clone -- would otherwise skip every test of the resolution rules, and
 * those rules are the part worth pinning down. The firmware never defines it. */
#if CONFIG_OHEZ_ICONS_BUILTIN
#if defined(ICON_SET_DATA_HEADER)
#include ICON_SET_DATA_HEADER
#elif defined(__has_include)
#if __has_include("icon_set_data.h")
#include "icon_set_data.h"
#endif
#endif
#endif

/* ------------------------------------------------------------ name handling */

bool icon_name_qualify(const char *name, const char *state, char *out, size_t out_size)
{
    if (name == NULL || state == NULL || state[0] == '\0')
        return false;

    int written = snprintf(out, out_size, "%s-%s", name, state);

    if (written < 0 || (size_t)written >= out_size)
        return false;

    for (char *c = out; *c != '\0'; ++c)
        *c = (char)tolower((unsigned char)*c);

    return true;
}

bool icon_url_split(const char *url, char *name, size_t name_size,
                    char *state, size_t state_size)
{
    name[0] = '\0';
    state[0] = '\0';

    if (url == NULL)
        return false;

    const char *segment = strstr(url, "/icon/");

    if (segment == NULL)
        return false;

    const char *name_begin = segment + strlen("/icon/");
    /* The name runs to the query string, or to the end for a URL without one. */
    const char *name_end = strchr(name_begin, '?');

    if (name_end == NULL)
        name_end = name_begin + strlen(name_begin);

    size_t name_len = (size_t)(name_end - name_begin);

    if (name_len == 0 || name_len >= name_size)
        return false;

    memcpy(name, name_begin, name_len);
    name[name_len] = '\0';

    const char *state_begin = strstr(name_end, "state=");

    if (state_begin != NULL)
    {
        state_begin += strlen("state=");

        /* "&format=png" follows in every URL iconUrl() builds, but the state is
         * the last parameter in a URL built by hand, so both endings count. */
        const char *state_end = strchr(state_begin, '&');

        if (state_end == NULL)
            state_end = state_begin + strlen(state_begin);

        size_t state_len = (size_t)(state_end - state_begin);

        if (state_len >= state_size)
            return false;

        memcpy(state, state_begin, state_len);
        state[state_len] = '\0';
    }

    return true;
}

const unsigned char *icon_set_get_by_url(const char *url, size_t *size)
{
    char name[ICON_SET_NAME_MAX];
    char state[ICON_SET_NAME_MAX];

    *size = 0;

    if (icon_url_split(url, name, sizeof(name), state, sizeof(state)) == false)
        return NULL;

    return icon_set_get(name, state, size);
}

/* ------------------------------------------------------------- the set itself */

#ifdef ICON_SET_GENERATED

/* Lowercase `src` into `dst`. False if it does not fit: a truncated name is a
 * different icon, and looking that one up is worse than finding nothing. */
static bool lower_copy(char *dst, size_t size, const char *src)
{
    size_t length = strlen(src);

    if (length >= size)
        return false;

    for (size_t i = 0; i < length; ++i)
        dst[i] = (char)tolower((unsigned char)src[i]);

    dst[length] = '\0';

    return true;
}

static const unsigned char *entry_data(size_t index, size_t *size)
{
    *size = icon_set_table[index].size;

    return icon_set_blob + icon_set_table[index].offset;
}

/* The table is sorted by name, by plain byte value -- the generator asserts it
 * -- so both of these are binary searches over a few hundred entries rather
 * than a walk. That matters less for the time than for where it happens: this
 * runs on the client task, once per tile, while the UI is drawing. */
static int find_exact(const char *name)
{
    size_t low = 0;
    size_t high = ICON_SET_COUNT;

    while (low < high)
    {
        size_t mid = low + (high - low) / 2;
        int    cmp = strcmp(name, icon_set_table[mid].name);

        if (cmp == 0)
            return (int)mid;

        if (cmp < 0)
            high = mid;
        else
            low = mid + 1;
    }

    return -1;
}

/* The highest "<name>-<number>" whose number does not exceed `value`.
 *
 * openHAB's own rule for a numeric state, and the reason it exists: an icon
 * with steps is drawn at the step the item has reached, so "light" -- which
 * ships light-0 through light-100 in tens -- resolves at 40 to "light-40", and
 * at 44 to the same one rather than to nothing.
 *
 * Only digits count as a step, and that is not pedantry: "light" also ships
 * light-off and light-on, which share the prefix and sit in this very run.
 * strtoul() reads "off" as 0. Families that have named variants and no numeric
 * ones at all -- contact, door, lock, presence, seventeen others -- are where
 * that goes visibly wrong: every numeric state would find a "step" of 0.
 *
 * Variants of one icon share a prefix and the table is sorted, so they sit in
 * one run; the search finds where that run starts and the loop leaves it at the
 * first name that is no longer part of it.
 */
static int find_numeric(const char *name, double value)
{
    char prefix[ICON_SET_NAME_MAX];
    int  written = snprintf(prefix, sizeof(prefix), "%s-", name);

    if (written < 0 || (size_t)written >= sizeof(prefix))
        return -1;

    size_t prefix_len = (size_t)written;
    size_t low = 0;
    size_t high = ICON_SET_COUNT;

    while (low < high)
    {
        size_t mid = low + (high - low) / 2;

        if (strncmp(icon_set_table[mid].name, prefix, prefix_len) < 0)
            low = mid + 1;
        else
            high = mid;
    }

    int    best = -1;
    double best_value = 0.0;

    for (size_t i = low; i < ICON_SET_COUNT; ++i)
    {
        const char *entry = icon_set_table[i].name;

        if (strncmp(entry, prefix, prefix_len) != 0)
            break;

        const char *suffix = entry + prefix_len;

        if (*suffix == '\0')
            continue;

        /* Digits only. "light-on" shares the prefix with "light-10" and is not
         * a step; strtoul() would read it as 0 and make it the answer for every
         * numeric state. */
        bool numeric = true;

        for (const char *c = suffix; *c != '\0'; ++c)
        {
            if (isdigit((unsigned char)*c) == 0)
            {
                numeric = false;
                break;
            }
        }

        if (numeric == false)
            continue;

        double candidate = (double)strtoul(suffix, NULL, 10);

        if (candidate <= value && (best < 0 || candidate > best_value))
        {
            best = (int)i;
            best_value = candidate;
        }
    }

    return best;
}

const unsigned char *icon_set_get(const char *name, const char *state, size_t *size)
{
    char lowered[ICON_SET_NAME_MAX];

    *size = 0;

    if (name == NULL || name[0] == '\0')
        return NULL;

    /* The table is lowercase throughout, because openHAB's icon names are; a
     * sitemap is under no such obligation about what it writes in one. */
    if (lower_copy(lowered, sizeof(lowered), name) == false)
        return NULL;

    if (state != NULL && state[0] != '\0')
    {
        char qualified[ICON_SET_NAME_MAX];

        if (icon_name_qualify(lowered, state, qualified, sizeof(qualified)) == true)
        {
            int index = find_exact(qualified);

            if (index >= 0)
                return entry_data((size_t)index, size);
        }

        /* Only for a state that is entirely a number: "40" is a dimmer, while
         * "120,100,50" is a colour and "ON" is neither, and strtod() would
         * happily read the first number out of any of them. */
        char  *end = NULL;
        double value = strtod(state, &end);

        if (end != state && *end == '\0')
        {
            int index = find_numeric(lowered, value);

            if (index >= 0)
                return entry_data((size_t)index, size);
        }
    }

    int index = find_exact(lowered);

    return (index >= 0) ? entry_data((size_t)index, size) : NULL;
}

size_t icon_set_count(void)
{
    return ICON_SET_COUNT;
}

size_t icon_set_bytes(void)
{
    return ICON_SET_BLOB_SIZE;
}

#else /* !ICON_SET_GENERATED */

const unsigned char *icon_set_get(const char *name, const char *state, size_t *size)
{
    (void)name;
    (void)state;

    *size = 0;

    return NULL;
}

size_t icon_set_count(void)
{
    return 0;
}

size_t icon_set_bytes(void)
{
    return 0;
}

#endif /* ICON_SET_GENERATED */
