/**
 * @file icon_fixture.hpp
 *
 * Widget icons for the host simulator (SIMULATOR == 1).
 *
 * The firmware fetches icon PNGs from openHAB over HTTP, which the simulator
 * cannot do. The icons are compiled in instead, from a header generated by
 *
 *     tools/fetch_sim_icons.py
 *
 * That header is deliberately not part of this repository: the openHAB classic
 * icon set is licensed under the EPL-2.0, which is incompatible with this
 * project's GPL-3.0. Until the script has been run the lookup below simply
 * finds nothing and the widgets are drawn without an icon, exactly as they are
 * when an icon request to a real server fails.
 */

#ifndef ICON_FIXTURE_HPP
#define ICON_FIXTURE_HPP

#include <stddef.h>

/**
 * Look up a compiled-in icon.
 *
 * As openHAB does, a state specific icon ("light-on" for the icon "light" in
 * state "ON") takes precedence over the plain one.
 *
 * @param name  icon name from the sitemap, e.g. "light"
 * @param state current item state, e.g. "ON"; may be NULL or empty
 * @param size  out: size of the returned PNG in bytes, 0 if none was found
 * @return pointer to the PNG data, or NULL if no icon is available
 */
const unsigned char *sim_icon_fixture_get(const char *name, const char *state, size_t *size);

#endif /* ICON_FIXTURE_HPP */
