/**
 * @file icon_fixture.cpp
 *
 * See icon_fixture.hpp.
 */

#include "sdkconfig.h"

#include "icon_fixture.hpp"

#include "icons/icon_set.hpp"

#include <string.h>

/* Generated by tools/fetch_sim_icons.py, and absent until it has been run.
 * Host-only: the device has an openHAB to ask, and no flash to spare for a
 * second copy of its icon set. So the lookup below is compiled either way and
 * simply finds nothing on the device -- which is also what it does on the host
 * before the script has run. */
#if CONFIG_IDF_TARGET_LINUX
#if defined(__has_include)
#if __has_include("icon_fixture_data.h")
#include "icon_fixture_data.h"
#endif
#endif
#endif

const unsigned char *sim_icon_fixture_get_by_url(const char *url, size_t *size)
{
    char name[ICON_SET_NAME_MAX];
    char state[ICON_SET_NAME_MAX];

    *size = 0;

    /* Taking the URL apart is icons/icon_set.cpp's job now, and was duplicated
     * here until the built-in set needed the same thing: one query string, one
     * place that reads it. */
    if (icon_url_split(url, name, sizeof(name), state, sizeof(state)) == false)
        return NULL;

    return sim_icon_fixture_get(name, state, size);
}

#ifdef SIM_ICON_FIXTURE_GENERATED

static const unsigned char *find_icon(const char *name, size_t *size)
{
    for (size_t i = 0; i < sizeof(sim_icon_table) / sizeof(sim_icon_table[0]); ++i)
    {
        if (strcmp(sim_icon_table[i].name, name) == 0)
        {
            *size = sim_icon_table[i].size;
            return sim_icon_table[i].data;
        }
    }

    return NULL;
}

const unsigned char *sim_icon_fixture_get(const char *name, const char *state, size_t *size)
{
    *size = 0;

    if (name == NULL || name[0] == '\0')
        return NULL;

    // Prefer the state specific icon, e.g. "light-on" over "light".
    if (state != NULL && state[0] != '\0')
    {
        char qualified[ICON_SET_NAME_MAX];

        if (icon_name_qualify(name, state, qualified, sizeof(qualified)) == true)
        {
            const unsigned char *icon = find_icon(qualified, size);

            if (icon != NULL)
                return icon;
        }
    }

    return find_icon(name, size);
}

#else /* !SIM_ICON_FIXTURE_GENERATED */

const unsigned char *sim_icon_fixture_get(const char *name, const char *state, size_t *size)
{
    (void)name;
    (void)state;

    *size = 0;
    return NULL;
}

#endif /* SIM_ICON_FIXTURE_GENERATED */
