/**
 * @file sitemap_fixture.cpp
 *
 * See sitemap_fixture.hpp.
 *
 * The JSON below is shaped like the responses of openHAB's
 * /rest/sitemaps/<sitemap>/<page> endpoint, and carries the fields a real
 * server sends rather than only the ones the connector reads -- checked
 * against openHAB 5.2.1 on 2026-09-15 and corrected to match it. The
 * difference is not cosmetic: `mappings` is present on *every* widget, empty
 * when the sitemap declares none, which decides which branch of the parser's
 * selection handling runs. A fixture that omitted it tested a path a real
 * server never takes.
 *
 * The three shapes worth knowing, all taken from that capture:
 *
 *   - a Group widget carries both its group item and a linkedPage;
 *   - `Text label="..." { ... }` becomes a Text widget with a linkedPage and
 *     no "item" key at all, which is the commonest way to make a sub-page;
 *   - a Player item arrives with PREVIOUS/PAUSE/PLAY/NEXT mappings openHAB
 *     generated by itself, from a bare `Default item=...` line.
 *
 * An item openHAB has no value for reads "NULL" -- the four characters, not a
 * JSON null -- and Light_Night is here to keep that shape in the fixture.
 *
 * Two more were settled by adding items to that server rather than reasoning
 * about it:
 *
 *   - a Group widget carries an item with "members", "groupType" and
 *     "function", and an aggregated state, so its tile is polled like any
 *     other. gLivingRoom is shaped like a real `Group:Switch:OR(ON,OFF)`.
 *   - a dimensioned item puts its unit in three places at once: on the state
 *     ("21.5 °C"), on the widget as "unit", and on the item as "unitSymbol".
 *     Weather_Temperature and Thermostat_Setpoint carry all three.
 *
 * Bedroom_Humidity is a plain Number and not the Number:Dimensionless it
 * looks like it should be, deliberately. openHAB normalises "48 %" on such an
 * item to the ratio 0.48 and formats a bare 48 as "4800 %", so neither
 * spelling renders the way this tile reads; the panel drops the unit and shows
 * "0 %" for the first. That divergence is pinned in test_item_state.cpp
 * instead of being baked into the screen the simulator opens on.
 *
 * Keep at most ITEM_COUNT_MAX (6) widgets per page, counting the implicit
 * "back" item that a page with a "parent" produces.
 */

#include "sdkconfig.h"

#include "sitemap_fixture.hpp"

#include <string.h>

/* The pages are host-only: 8 KB of demo JSON is worth its space in a simulator
 * and not in a firmware image, and the device has a real server to ask. The
 * lookup is compiled either way and finds nothing there. */
#if CONFIG_IDF_TARGET_LINUX

#define FIXTURE_BASE "http://localhost:8080"

/*
 * Home: two sub pages plus a few read-only and switchable items.
 */
static const char page_demo[] = R"json(
{
  "id": "demo",
  "title": "OhEzTouch Demo",
  "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/demo/demo",
  "leaf": false,
  "timeout": false,
  "widgets": [
    {
      "widgetId": "0000",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/gLivingRoom",
        "state": "OFF",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "members": [],
        "function": {
          "name": "OR",
          "params": [
            "ON",
            "OFF"
          ]
        },
        "type": "Group",
        "name": "gLivingRoom",
        "label": "Living Room",
        "category": "sofa",
        "tags": [],
        "groupNames": [],
        "groupType": "Switch"
      },
      "linkedPage": {
        "id": "living",
        "title": "Living Room",
        "icon": "sofa",
        "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/demo/living",
        "leaf": false,
        "timeout": false
      },
      "widgets": [],
      "mappings": [],
      "type": "Group",
      "label": "Living Room",
      "icon": "sofa",
      "staticIcon": false
    },
    {
      "widgetId": "0001",
      "visibility": true,
      "labelSource": "SITEMAP_WIDGET",
      "unit": "",
      "linkedPage": {
        "id": "bedroom",
        "title": "Bedroom",
        "icon": "bedroom",
        "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/demo/bedroom",
        "leaf": false,
        "timeout": false
      },
      "widgets": [],
      "mappings": [],
      "type": "Text",
      "label": "Bedroom",
      "icon": "bedroom",
      "staticIcon": false
    },
    {
      "widgetId": "0002",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "pattern": "%.1f °C",
      "unit": "°C",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Weather_Temperature",
        "state": "3.5 °C",
        "stateDescription": {
          "pattern": "%.1f °C",
          "readOnly": true,
          "options": []
        },
        "lastState": "3.5 °C",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "unitSymbol": "°C",
        "type": "Number:Temperature",
        "name": "Weather_Temperature",
        "label": "Outside Temperature",
        "category": "temperature",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Text",
      "label": "Outside Temperature [3.5 °C]",
      "icon": "temperature",
      "staticIcon": false
    },
    {
      "widgetId": "0003",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "pattern": "%s",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Doorbell_Status",
        "state": "idle",
        "stateDescription": {
          "pattern": "%s",
          "readOnly": true,
          "options": []
        },
        "lastState": "idle",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "String",
        "name": "Doorbell_Status",
        "label": "Doorbell",
        "category": "text",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Text",
      "label": "Doorbell [idle]",
      "icon": "text",
      "staticIcon": false
    },
    {
      "widgetId": "0004",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/gLights",
        "state": "OFF",
        "lastState": "OFF",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "Group",
        "name": "gLights",
        "label": "All Lights",
        "category": "light",
        "tags": [],
        "groupNames": [],
        "groupType": "Switch"
      },
      "widgets": [],
      "mappings": [],
      "type": "Switch",
      "label": "All Lights",
      "icon": "light",
      "staticIcon": false
    },
    {
      "widgetId": "0005",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "pattern": "%d %%",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Light_Hallway",
        "state": "40",
        "lastState": "40",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "Dimmer",
        "name": "Light_Hallway",
        "label": "Hallway Dimmer",
        "category": "slider",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Slider",
      "label": "Hallway Dimmer [40 %]",
      "icon": "slider",
      "staticIcon": false,
      "switchSupport": false,
      "releaseOnly": false,
      "minValue": 0,
      "maxValue": 100,
      "step": 1
    }
  ]
}
)json";

/*
 * Living Room: the interactive widget types.
 */
static const char page_living[] = R"json(
{
  "id": "living",
  "title": "Living Room",
  "icon": "sofa",
  "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/demo/living",
  "parent": {
    "id": "demo",
    "title": "OhEzTouch Demo",
    "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/demo/demo",
    "leaf": false,
    "timeout": false
  },
  "leaf": true,
  "timeout": false,
  "widgets": [
    {
      "widgetId": "1000",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Light_Ceiling",
        "state": "ON",
        "lastState": "ON",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "Switch",
        "name": "Light_Ceiling",
        "label": "Ceiling Light",
        "category": "light",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Switch",
      "label": "Ceiling Light",
      "icon": "light",
      "staticIcon": false
    },
    {
      "widgetId": "1001",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "pattern": "%d %%",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Light_Floor",
        "state": "75",
        "lastState": "75",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "Dimmer",
        "name": "Light_Floor",
        "label": "Floor Lamp",
        "category": "slider",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Slider",
      "label": "Floor Lamp [75 %]",
      "icon": "slider",
      "staticIcon": false,
      "switchSupport": false,
      "releaseOnly": false
    },
    {
      "widgetId": "1002",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Light_Strip_Color",
        "state": "200,80,60",
        "lastState": "200,80,60",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "Color",
        "name": "Light_Strip_Color",
        "label": "RGB Strip",
        "category": "colorlight",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Colorpicker",
      "label": "RGB Strip",
      "icon": "colorpicker",
      "staticIcon": false
    },
    {
      "widgetId": "1003",
      "visibility": true,
      "labelSource": "SITEMAP_WIDGET",
      "pattern": "%.1f °C",
      "unit": "°C",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Thermostat_Setpoint",
        "state": "21.5 °C",
        "stateDescription": {
          "pattern": "%.1f °C",
          "readOnly": false,
          "options": []
        },
        "lastState": "21.5 °C",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "unitSymbol": "°C",
        "type": "Number:Temperature",
        "name": "Thermostat_Setpoint",
        "label": "Thermostat",
        "category": "heating",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Setpoint",
      "label": "Thermostat [21.5 °C]",
      "icon": "heating",
      "staticIcon": false,
      "minValue": 10,
      "maxValue": 28,
      "step": 0.5
    },
    {
      "widgetId": "1004",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Living_Scene",
        "state": "READING",
        "lastState": "READING",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "String",
        "name": "Living_Scene",
        "label": "Scene",
        "category": "settings",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [
        {
          "command": "MOVIE",
          "label": "Movie"
        },
        {
          "command": "READING",
          "label": "Reading"
        },
        {
          "command": "PARTY",
          "label": "Party"
        },
        {
          "command": "OFF",
          "label": "Off"
        }
      ],
      "type": "Selection",
      "label": "Scene",
      "icon": "settings",
      "staticIcon": false
    }
  ]
}
)json";

/*
 * Bedroom: rollershutter and player, and a number with a percent pattern.
 */
static const char page_bedroom[] = R"json(
{
  "id": "bedroom",
  "title": "Bedroom",
  "icon": "bedroom",
  "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/demo/bedroom",
  "parent": {
    "id": "demo",
    "title": "OhEzTouch Demo",
    "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/demo/demo",
    "leaf": false,
    "timeout": false
  },
  "leaf": true,
  "timeout": false,
  "widgets": [
    {
      "widgetId": "2000",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Blinds_Bedroom",
        "state": "30",
        "lastState": "30",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "Rollershutter",
        "name": "Blinds_Bedroom",
        "label": "Blinds",
        "category": "rollershutter",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Switch",
      "label": "Blinds",
      "icon": "rollershutter",
      "staticIcon": false
    },
    {
      "widgetId": "2001",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Radio_Control",
        "state": "PAUSE",
        "lastState": "PAUSE",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "Player",
        "name": "Radio_Control",
        "label": "Radio",
        "category": "receiver",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [
        {
          "command": "PREVIOUS",
          "label": "<<"
        },
        {
          "command": "PAUSE",
          "label": "||"
        },
        {
          "command": "PLAY",
          "label": ">"
        },
        {
          "command": "NEXT",
          "label": ">>"
        }
      ],
      "type": "Switch",
      "label": "Radio",
      "icon": "receiver",
      "staticIcon": false
    },
    {
      "widgetId": "2002",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "pattern": "%d %%",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Bedroom_Humidity",
        "state": "48",
        "stateDescription": {
          "pattern": "%d %%",
          "readOnly": true,
          "options": []
        },
        "lastState": "48",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "Number",
        "name": "Bedroom_Humidity",
        "label": "Humidity",
        "category": "humidity",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Text",
      "label": "Humidity [48 %]",
      "icon": "humidity",
      "staticIcon": false
    },
    {
      "widgetId": "2003",
      "visibility": true,
      "labelSource": "ITEM_LABEL",
      "unit": "",
      "item": {
        "link": ")json" FIXTURE_BASE R"json(/rest/items/Light_Night",
        "state": "NULL",
        "lastState": "NULL",
        "lastStateUpdate": 1789466761867,
        "lastStateChange": 1789466761867,
        "type": "Switch",
        "name": "Light_Night",
        "label": "Night Light",
        "category": "light",
        "tags": [],
        "groupNames": []
      },
      "widgets": [],
      "mappings": [],
      "type": "Switch",
      "label": "Night Light",
      "icon": "light",
      "staticIcon": false
    }
  ]
}
)json";

/* The list endpoint's answer. The "homepage" objects are here because a real
 * server sends them and because the parser's filter is what keeps them out of
 * the document; a fixture without them would test a path no server takes.
 *
 * "demo" is the sitemap the pages above are, so picking it in offline mode
 * lands on a screen. The other two exist to make the list a list -- they have
 * no fixture behind them, and choosing one shows what a sitemap the server
 * does not really serve looks like: the page fetch fails and the panel says
 * so. */
static const char sitemap_list[] = R"json(
[
  {
    "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/demo",
    "homepage": {
      "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/demo/demo",
      "leaf": false,
      "timeout": false,
      "widgets": []
    },
    "name": "demo",
    "label": "OhEzTouch Demo"
  },
  {
    "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/kitchen",
    "homepage": {
      "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/kitchen/kitchen",
      "leaf": false,
      "timeout": false,
      "widgets": []
    },
    "name": "kitchen",
    "label": "Kitchen Panel"
  },
  {
    "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/garden",
    "homepage": {
      "link": ")json" FIXTURE_BASE R"json(/rest/sitemaps/garden/garden",
      "leaf": false,
      "timeout": false,
      "widgets": []
    },
    "name": "garden"
  }
]
)json";

/* Keyed by page name, not by full path: openHAB's own URL for a sitemap's home
 * page is /rest/sitemaps/<sitemap>/<sitemap>, so keying on the path would mean
 * the simulator only rendered anything when config.json happened to name the
 * sitemap "demo". The page name is what actually identifies a page. */
static const struct
{
    const char *page;
    const char *body;
} fixture_pages[] = {
    { "living",  page_living  },
    { "bedroom", page_bedroom },
};

const char *sim_sitemap_fixture_get(const char *url)
{
    if (url == NULL)
        return NULL;

    /* Skip the scheme and authority, so that the configured host and port do
     * not have to match the fixture. */
    const char *path = strstr(url, "/rest/sitemaps/");
    if (path == NULL)
        return NULL;

    path += strlen("/rest/sitemaps/");

    /* /<sitemap>/<page>, then the query string. */
    size_t sitemap_len = strcspn(path, "/");
    if (path[sitemap_len] != '/')
        return NULL;

    const char *page = path + sitemap_len + 1;
    size_t page_len = strcspn(page, "?");

    /* The home page is the one whose name equals the sitemap's, whatever that
     * happens to be. */
    if (page_len == sitemap_len && strncmp(page, path, page_len) == 0)
        return page_demo;

    for (size_t i = 0; i < sizeof(fixture_pages) / sizeof(fixture_pages[0]); ++i)
    {
        if (   strlen(fixture_pages[i].page) == page_len
            && strncmp(fixture_pages[i].page, page, page_len) == 0)
        {
            return fixture_pages[i].body;
        }
    }

    return NULL;
}

const char *sim_sitemap_fixture_list(void)
{
    return sitemap_list;
}

#else /* !CONFIG_IDF_TARGET_LINUX */

const char *sim_sitemap_fixture_get(const char *url)
{
    (void)url;
    return NULL;
}

const char *sim_sitemap_fixture_list(void)
{
    return NULL;
}

#endif /* CONFIG_IDF_TARGET_LINUX */
