/**
 * @file icon_fixture.cpp
 *
 * See icon_fixture.hpp.
 */

#if (SIMULATOR == 1)

#include "icon_fixture.hpp"

#include <ctype.h>
#include <stdio.h>
#include <string.h>

/* Generated by tools/fetch_sim_icons.py, and absent until it has been run. */
#if defined(__has_include)
#if __has_include("icon_fixture_data.h")
#include "icon_fixture_data.h"
#endif
#endif

#ifdef SIM_ICON_FIXTURE_GENERATED

static const unsigned char *find_icon(const char *name, size_t *size)
{
    for (size_t i = 0; i < sizeof(sim_icon_table) / sizeof(sim_icon_table[0]); ++i)
    {
        if (strcmp(sim_icon_table[i].name, name) == 0)
        {
            *size = sim_icon_table[i].size;
            return sim_icon_table[i].data;
        }
    }

    return NULL;
}

const unsigned char *sim_icon_fixture_get(const char *name, const char *state, size_t *size)
{
    *size = 0;

    if (name == NULL || name[0] == '\0')
        return NULL;

    // Prefer the state specific icon, e.g. "light-on" over "light".
    if (state != NULL && state[0] != '\0')
    {
        char qualified[64];

        if (snprintf(qualified, sizeof(qualified), "%s-%s", name, state) < (int)sizeof(qualified))
        {
            for (char *c = qualified; *c != '\0'; ++c)
                *c = (char)tolower((unsigned char)*c);

            const unsigned char *icon = find_icon(qualified, size);
            if (icon != NULL)
                return icon;
        }
    }

    return find_icon(name, size);
}

#else /* !SIM_ICON_FIXTURE_GENERATED */

const unsigned char *sim_icon_fixture_get(const char *name, const char *state, size_t *size)
{
    (void)name;
    (void)state;

    *size = 0;
    return NULL;
}

#endif /* SIM_ICON_FIXTURE_GENERATED */

#endif /* #if (SIMULATOR == 1) */
